language: cpp

script:
  - cmake -H. -Bbuild
  - cmake --build build
  - ./build/CI_usage

env:
  - COMPILER=g++-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - g++-6
