language: cpp

install:
  - ./install.sh

script:
  - ./run.sh

env:
  - BUILD_TYPE=Debug COMPILER=g++-6
  - BUILD_TYPE=Debug COMPILER=clang++-4.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages:
    - g++-6
    - clang-4.0
