language: cpp

sudo:
  required

install:
  - ./install.sh

script:
  - ./run.sh

env:
  - BUILD_TYPE=Debug CXX_COMPILER=clang++-4.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - clang-4.0
